service: sg-code-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  index:
    handler: dist/bundle.userHandler.index
    events:
      - httpApi:
          path: /user
          method: get
  create:
    handler: dist/bundle.userHandler.create
    role: writeRightsRole 
    events:
      - httpApi:
          path: /user
          method: post
  update:
    handler: dist/bundle.userHandler.update
    role: writeRightsRole 
    events:
      - httpApi:
          path: /user
          method: put
  delete:
    handler: dist/bundle.userHandler.delete
    role: deleteRightsRole 
    events:
      - httpApi:
          path: /user
          method: delete

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tb_user
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    readRightsRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /sg/challenge/
        RoleName: WriteDynamoRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: WritePolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:Scan
                    - dynamodb:GetItem
                  Resource: "arn:aws:dynamodb:*:*:table/tb_user" 
    writeRightsRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /sg/challenge/
        RoleName: WriteDynamoRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: WritePolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource: "arn:aws:dynamodb:*:*:table/tb_user" 
    deleteRightsRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /sg/challenge/
        RoleName: DeleteDynamoRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DeletePolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:DeleteItem
                  Resource: "arn:aws:dynamodb:*:*:table/tb_user" 