service: sg-code-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  index:
    handler: dist/bundle.userHandler.index
    events:
      - httpApi:
          path: /user
          method: get
  create:
    handler: dist/bundle.userHandler.create
    events:
      - httpApi:
          path: /user
          method: post
  update:
    handler: dist/bundle.userHandler.update
    events:
      - httpApi:
          path: /user
          method: put
  delete:
    handler: dist/bundle.userHandler.delete
    events:
      - httpApi:
          path: /user
          method: delete

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tb_user
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH