on:
  pull_request:
    types: [closed]
    branches:
      - 'develop'

jobs:
  ci:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: '16.19.1'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: create pull request
        run: gh pr create -B master -H $BRANCH_NAME --title 'Merge develop into master' --body 'Automatically created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            ./dist
            ./serverless.yml
  cd:
    runs-on: ubuntu-latest
    needs: ci
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
      - name: printenv
        run: printenv
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: my-artifact
      - run: ls -la
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Deploy Dev
        run: sls deploy --stage develop
