name: Destroy infrastructure

on:
  issues:
    types: [closed]

jobs:
  closed:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

    steps:
      - uses: actions/checkout@v4
      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: '16.19.1'
      - name: Verifying issue
        id: issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const issue = context.payload.issue;
            const label = "destroy";
            if (issue.labels.find(l => l.name === label)) {
              return "true";
            } else {
              return "false";
            }
      - name: Install Serverless Framework
        if: steps.issue.outputs.result == 'true'
        run: npm install -g serverless
      - name: Destroy
        if: steps.issue.outputs.result == 'true'
        run: |
          sls remove -s develop
          sls remove