name: Create Pull Request to Develop

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create pull request
        run: gh pr create -B $BRANCH_NAME -H origin/develop --title 'Merge $BRANCH_NAME into develop' --body 'Automatically created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 